### ISSUE TITLE
Google Maps tutorial link is not directing to the documentation

### ISSUE THREAD

**Issue by juanpflores** [MLH/mlh-localhost-github#1402]
Hey MLH Team 👋 
I've checked the tutorial link mentioned in the [Google Maps section](https://github.com/MLH/mlh-localhost-github#google-maps-api-key) in the README file and it is not redirecting to the documentation. It seems like the `/docs` folder is no longer available in this repository or not public (?). A solution could be to delete the link toi the tutorial or make the dos folder available again. 

😅

**Comment by nquinlan** [comment]
Good catch @juanpflores! Turns out we moved the "tutorial" into the readme, removed the line.
