### ISSUE TITLE
Map is not showing

### ISSUE THREAD

**Issue by whyadiwhy** [MLH/mlh-localhost-github#1663]
![MLH Localhost Map - Google Chrome 12_27_2020 7_22_50 PM](https://user-images.githubusercontent.com/40954187/103172399-255c9800-4879-11eb-9d3e-321a6685ef8e.png)

the page was loaded completely but the map was not showing.
https://mlh-localhost-hometowns.herokuapp.com/

**Comment by nquinlan** [comment]
Fixed! Turns out it was an API key error.
