### ISSUE TITLE
BUG: Map view broken due to Antarctica

### ISSUE THREAD

**Issue by Vyvy-vi** [MLH/mlh-localhost-github#1732]
I think I broke the map in PR no. - #1677 by adding Antarctica in the hometown list.
Screenshot:
![Screenshot 2021-01-23 at 12 41 35 AM](https://user-images.githubusercontent.com/62864373/105535030-59aa6380-5d14-11eb-87ef-50b8ed3b51bb.png)

**Comment by nquinlan** [comment]
Fixed!
