### ISSUE TITLE
Google Maps not displaying correctly

### ISSUE THREAD

**Issue by vincentiroleh** [MLH/mlh-localhost-github#286]
Google Maps is not displaying correctly, this could be an issue with the `Google Maps Platform Billing` 
@JamieMLH 
![Screenshot from 2019-10-07 19-10-25](https://user-images.githubusercontent.com/16861948/66337179-94796400-e936-11e9-9223-43c85bd72b74.png)

**Comment by Raymo111** [comment]
@vincentiroleh You need to add your own Google Maps API key to a .env file.

**Comment by Owinoh-victor** [comment]
You have to do environment setup for your device. You can achieve that by adding Google Maps API key to your program environment
