### ISSUE TITLE
Map doesn't show pins

### ISSUE THREAD

**Issue by AdrianaCaetano** [MLH/mlh-localhost-github#743]
I'm hosting a MLH workshop today, but the map is not showing the pins. 
https://mlh-localhost-hometowns.herokuapp.com
<img width="1235" alt="Screen Shot 2019-11-18 at 8 52 03 AM" src="https://user-images.githubusercontent.com/52258921/69072548-b576af80-09e0-11ea-95fb-969f3faec850.png">

**Comment by Raymo111** [comment]
@AdrianaCaetano How did you get it to work? It shows them now, but I'm having the same problem.

**Comment by edwincarbajal** [comment]
@Raymo111 thanks for sharing the fix to this problem!
